# Licensed to the Apache Software Foundation (ASF) under one
# or more contributor license agreements.  See the NOTICE file
# distributed with this work for additional information
# regarding copyright ownership.  The ASF licenses this file
# to you under the Apache License, Version 2.0 (the
# "License"); you may not use this file except in compliance
# with the License.  You may obtain a copy of the License at
#
#   http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing,
# software distributed under the License is distributed on an
# "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY
# KIND, either express or implied.  See the License for the
# specific language governing permissions and limitations
# under the License.

name: Windows MSVC C GLib
on:
  - push
  - pull_request
jobs:
  build:
    name: Build
    strategy:
      matrix:
        label:
          - "2019"
          - "2017"
        include:
          - label: "2019"
            os: windows-2019
            visual-studio-year: 2019
            cmake-generator: Visual Studio 16 2019
            meson-backend: vs2019
          - label: "2017"
            os: windows-2016
            visual-studio-year: 2017
            cmake-generator: Visual Studio 15 2017
            meson-backend: vs2017
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@master
      - name: "C++: CMake"
        run: |
          mkdir build\cpp
          cmake ^
            -G "${{ matrix.cmake-generator }}" ^
            -A x64 ^
            -DARROW_USE_GLOG=OFF ^
            -DARROW_WITH_LZ4=OFF ^
            -DARROW_WITH_ZLIB=OFF ^
            -DCMAKE_INSTALL_PREFIX=%CD%\install ^
            -S cpp ^
            -B build\cpp
      - name: "C++: Install"
        run: |
          cmake --build build\cpp --config Debug --target Install
      - uses: actions/setup-python@v1
      - name: "C GLib: Install Meson"
        run: |
          pip install meson
      - name: "C GLib: Install GLib"
        run: |
          vcpkg install glib:x64-windows
      - name: "C GLib: Meson"
        run: |
          call "C:\Program Files (x86)\Microsoft Visual Studio\${{ matrix.visual-studio-year }}\Enterprise\VC\Auxiliary\Build\vcvars64.bat
          meson ^
            setup ^
            --backend=${{ matrix.meson-backend }} ^
            --cmake-prefix-path=%CD%\install ^
            --prefix=%CD%\install ^
            -Dintrospection=false ^
            -Dvcpkg_prefix=c:\vcpkg\installed\x64-windows ^
            build\c_glib ^
            c_glib
      - name: "C GLib: Install"
        run: |
          msbuild -target:all;install build\c_glib
